---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  become: true

- name: 'Nginx install'
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - nginx
