---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  become: true

- name: 'Nginx install'
  apt:
    name: "nginx"
    state: latest
  become: yes

- name: 'Configura index.html file'
  copy:
    src: 'files/index.html'
    dest: '/usr/share/nginx/html/index.html'
  become: yes
  notify:
    - restart nginx
